module Syntax = Syntax
module Parsing = Parsing
module Typing = Typing
module Runtime = Runtime
module Ir = Ir
module Loc = Loc
module Value = Value
module Provider = Provider
module Provider_schema = Provider_schema
module Provider_prompt = Provider_prompt
module Effect_request = Effect_request
module Effect_bridge = Effect_bridge
module Rpc_protocol = Rpc_protocol
module Rpc_stdio = Rpc_stdio
module Rpc_server = Rpc_server
module Lsp_analysis = Lsp_analysis
module Lsp_server = Lsp_server
module Providers_codex = Providers_codex
module Providers_opencode = Providers_opencode
module Providers = Providers
module Cli = Cli
module Project_config = Project_config

let version = "0.2.0-dev"
let about = "CamlFlow MVP: typed parser, checker, IR, runtime, and CLI." 
